#!/bin/sh

#####
## Sets the machine name to be formatted currentusername-serialnumber
#####

serial_no=$(ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{print $(NF-1)}' | tail)
currentUser=$(ls -l /dev/console | cut -d " " -f 4)

computer_name="${currentUser}-${serial_no}"

/usr/sbin/scutil --set LocalHostName "${computer_name}"
/usr/sbin/scutil --set ComputerName "${computer_name}"
/usr/sbin/scutil --set HostName "${computer_name}"

dscacheutil -flushcache
